/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ua.net.nlp.api

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

import groovy.transform.CompileStatic

@SpringBootApplication
@CompileStatic
public class App {
    static void main(String[] args) {
        SpringApplication.run App, args
    }
}
